---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: secureblue-custom
description: Personal build of secureblue Kinoite

base-image: ghcr.io/secureblue/kinoite-main-hardened
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: fonts
    fonts:
      nerd-fonts:
       - JetBrainsMono
      google-fonts:
       - Noto Sans
       - Poppins

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://openrazer.github.io/hardware:razer.repo
    install:
      - kitty
      - kvantum
      - neovim
      - tailscale
    remove:
      # -

  - type: akmods
    base: main
    install:
      - openrazer
      - v4l2loopback

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
